dist: bionic
language: node_js
cache: npm
node_js:
  - lts/*

addons:
  chrome: stable

services:
  - xvfb

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0

before_script:
  - export NODE_OPTIONS=--max_old_space_size=16000
  - npm install

script:
  - ng lint
  - npm run buildprod
  - ng e2e
