sudo: required
dist: trusty
language: node_js
cache: yarn
node_js:
  - '8.0'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - yarn global add @angular/cli --ignore-engines
  - yarn install --ignore-engines

script: 
  - ng lint
  - yarn buildprod
  - ng e2e
