sudo: required
dist: trusty
language: node_js
cache: yarn
node_js:
  - lts/*

addons:
  chrome: stable

before_install:
  - npm install -g yarn
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - yarn global add @angular/cli
  - yarn install

script:
  - ng lint
  - yarn buildprod
  - ng e2e
